import { Batch } from '../models/index.js';

export const createBatch = async (req, res) => {
  try {
    const { batch_name } = req.body; // Matches 'batch_name' in your SQL schema

    if (!batch_name) {
      return res.status(400).json({ message: "batch_name is required" });
    }

    // .create() is the Sequelize equivalent of 'INSERT INTO Batch ...'
    // batch_id is auto-generated by the database
    const newBatch = await Batch.create({ batch_name });

    res.status(201).json({
      message: "Batch created successfully",
      data: newBatch
    });
  } catch (error) {
    // Handles 'UNIQUE' constraint errors from your SQL schema
    if (error.name === 'SequelizeUniqueConstraintError') {
      return res.status(400).json({ message: "Batch name already exists" });
    }
    res.status(500).json({ message: "Error creating batch", error: error.message });
  }
};

export const getAllBatches = async (req, res) => {
  try {
    const batches = await Batch.findAll();
    res.status(200).json({
      message: "Batches retrieved successfully",
      data: batches
    });
  } catch (error) {
    res.status(500).json({ message: "Error retrieving batches", error: error.message });
  }
};

export const getBatchById = async (req, res) => {
  try {
    const { id } = req.params;
    const batch = await Batch.findByPk(id);

    if (!batch) {
      return res.status(404).json({ message: "Batch not found" });
    }

    res.status(200).json({
      message: "Batch retrieved successfully",
      data: batch
    });
  } catch (error) {
    res.status(500).json({ message: "Error retrieving batch", error: error.message });
  }
};

export const updateBatch = async (req, res) => {
  try {
    const { id } = req.params;
    const { batch_name } = req.body;

    const batch = await Batch.findByPk(id);

    if (!batch) {
      return res.status(404).json({ message: "Batch not found" });
    }

    await batch.update({ batch_name });

    res.status(200).json({
      message: "Batch updated successfully",
      data: batch
    });
  } catch (error) {
    if (error.name === 'SequelizeUniqueConstraintError') {
      return res.status(400).json({ message: "Batch name already exists" });
    }
    res.status(500).json({ message: "Error updating batch", error: error.message });
  }
};

export const deleteBatch = async (req, res) => {
  try {
    const { id } = req.params;
    const batch = await Batch.findByPk(id);

    if (!batch) {
      return res.status(404).json({ message: "Batch not found" });
    }

    await batch.destroy();

    res.status(200).json({
      message: "Batch deleted successfully"
    });
  } catch (error) {
    res.status(500).json({ message: "Error deleting batch", error: error.message });
  }
};